name: Build and Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: macos-latest
    #runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
<<<<<<< HEAD
        version: '1.7'
=======
        version: '1'
>>>>>>> 96b742c29838c5a74b68b9453c53f3487c5a9e26

    # GMT + ghostscript deps
    - run: brew install ghostscript gmt
    - run: echo $(gmt --version)

    #- name: Install Ghostscript (Windows)
      #run: >
<<<<<<< HEAD
        #choco install ghostscript wget
    #- run: wget http://fct-gmt.ualg.pt/gmt/data/wininstallers/gmt-win64.exe
    #- run: cmd /k gmt-win64.exe /S
=======
        #choco install ghostscript
>>>>>>> 96b742c29838c5a74b68b9453c53f3487c5a9e26

    - run: julia -e '
            using Pkg;
            Pkg.activate(".");
            Pkg.instantiate();
            Pkg.add(PackageSpec(name="GMT", rev="master"));
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js`);
            run(`$(npm_cmd()) install cheerio`);
            run(`$(npm_cmd()) install lunr`);
<<<<<<< HEAD
            using Xranklin;
=======
            using Franklin;
>>>>>>> 96b742c29838c5a74b68b9453c53f3487c5a9e26
            serve(single=true, cleanup=false);
            lunr();
            optimize(minify=false, prerender=false);'
    - name: Build and Deploy
<<<<<<< HEAD
      uses: JamesIves/github-pages-deploy-action@releases/v4
=======
      uses: JamesIves/github-pages-deploy-action@releases/v3
>>>>>>> 96b742c29838c5a74b68b9453c53f3487c5a9e26
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: __site
